name: deploy-sg
on: 
  # repository_dispatch:
  #   types:['build-docker-local']
  pull_request:
  push:
    
env:
  TEMP_BUILD: opd-16-temp
  CONTAINER_NAME: opd-16
  CONTAINER_IMAGE: nirun:latest
  CONTAINER_IMAGE_DEPLOY: nirun:deploy
  NIRUN_DOCKER_BRANCH: max-dev 
jobs:
  deploy-sg:
    runs-on: self-hosted
    environment: secrets-nirun
    steps:
      - name: Build docker
        uses: appleboy/ssh-action@v1.0.0
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            key: ${{ secrets.PRIVATE_SSH_KEY }}
            port: ${{ secrets.SSH_PORT }}
            script: |
                cd ${{ env.TEMP_BUILD }}/docker
                git pull
                pwd
                mkdir odoo
                mkdir addons
                ls -alh
                docker stack rm ${{ env.CONTAINER_NAME }} || true
                sleep 8
                echo HOST=${{ secrets.POSTGRES_HOST }} > env.env
                echo PORT=${{ secrets.POSTGRES_PORT }} >> env.env
                echo USER=${{ secrets.POSTGRES_USER }} >> env.env
                echo PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> env.env
                docker image rm ${{ env.CONTAINER_IMAGE_DEPLOY }} || true
                docker tag ${{ env.CONTAINER_IMAGE }} ${{ env.CONTAINER_IMAGE_DEPLOY }}
                docker stack deploy -c ./stack.yml ${{ env.CONTAINER_NAME }}
                sleep 8
                docker stack ps ${{ env.CONTAINER_NAME }}
                sleep 15
                docker service logs ${{ env.CONTAINER_NAME }}_opd-16
